// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkcomymfasugmwrkrewa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrY29teW1mYXN1Z213cmtyZXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMDU5NDIsImV4cCI6MjA1NDU4MTk0Mn0.p40VgMTZaDhpGzwMZQk3Qm6SZ7KCjl9mhWarWSbvhsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);